version: "3.9"
services:
  api:
    build: 
      context: .
      dockerfile: api.dockerfile
    ports:
      - "8084:8084"
    environment:
      PORT: ":8084"
      REDIS_URL: "redis:6379"
      ROOT_URL: "http://localhost:8084"
  docs:
    build: 
      context: .
      dockerfile: docs.dockerfile
    ports:
      - "8085:80"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"