global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: prometheus
    scrape_interval: 10s
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: api
    scrape_interval: 10s
    static_configs:
      - targets: ['api:8084']