// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: proto/URLShortenerV1.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateShortlinkReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url              string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	ExpiresInSeconds *int32 `protobuf:"varint,2,opt,name=expires_in_seconds,json=expiresInSeconds,proto3,oneof" json:"expires_in_seconds,omitempty"`
}

func (x *CreateShortlinkReq) Reset() {
	*x = CreateShortlinkReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_URLShortenerV1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateShortlinkReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortlinkReq) ProtoMessage() {}

func (x *CreateShortlinkReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_URLShortenerV1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortlinkReq.ProtoReflect.Descriptor instead.
func (*CreateShortlinkReq) Descriptor() ([]byte, []int) {
	return file_proto_URLShortenerV1_proto_rawDescGZIP(), []int{0}
}

func (x *CreateShortlinkReq) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CreateShortlinkReq) GetExpiresInSeconds() int32 {
	if x != nil && x.ExpiresInSeconds != nil {
		return *x.ExpiresInSeconds
	}
	return 0
}

type CreateShortlinkResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortUrl string `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
}

func (x *CreateShortlinkResp) Reset() {
	*x = CreateShortlinkResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_URLShortenerV1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateShortlinkResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortlinkResp) ProtoMessage() {}

func (x *CreateShortlinkResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_URLShortenerV1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortlinkResp.ProtoReflect.Descriptor instead.
func (*CreateShortlinkResp) Descriptor() ([]byte, []int) {
	return file_proto_URLShortenerV1_proto_rawDescGZIP(), []int{1}
}

func (x *CreateShortlinkResp) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type HealthChecpReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HealthChecpReq) Reset() {
	*x = HealthChecpReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_URLShortenerV1_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealthChecpReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthChecpReq) ProtoMessage() {}

func (x *HealthChecpReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_URLShortenerV1_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthChecpReq.ProtoReflect.Descriptor instead.
func (*HealthChecpReq) Descriptor() ([]byte, []int) {
	return file_proto_URLShortenerV1_proto_rawDescGZIP(), []int{2}
}

type HealthCheckResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *HealthCheckResp) Reset() {
	*x = HealthCheckResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_URLShortenerV1_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealthCheckResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResp) ProtoMessage() {}

func (x *HealthCheckResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_URLShortenerV1_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResp.ProtoReflect.Descriptor instead.
func (*HealthCheckResp) Descriptor() ([]byte, []int) {
	return file_proto_URLShortenerV1_proto_rawDescGZIP(), []int{3}
}

func (x *HealthCheckResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type RemoveShortlinkReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortUrl string `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
}

func (x *RemoveShortlinkReq) Reset() {
	*x = RemoveShortlinkReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_URLShortenerV1_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveShortlinkReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveShortlinkReq) ProtoMessage() {}

func (x *RemoveShortlinkReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_URLShortenerV1_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveShortlinkReq.ProtoReflect.Descriptor instead.
func (*RemoveShortlinkReq) Descriptor() ([]byte, []int) {
	return file_proto_URLShortenerV1_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveShortlinkReq) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type RemoveShortlinkResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Removed bool `protobuf:"varint,1,opt,name=removed,proto3" json:"removed,omitempty"`
}

func (x *RemoveShortlinkResp) Reset() {
	*x = RemoveShortlinkResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_URLShortenerV1_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveShortlinkResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveShortlinkResp) ProtoMessage() {}

func (x *RemoveShortlinkResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_URLShortenerV1_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveShortlinkResp.ProtoReflect.Descriptor instead.
func (*RemoveShortlinkResp) Descriptor() ([]byte, []int) {
	return file_proto_URLShortenerV1_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveShortlinkResp) GetRemoved() bool {
	if x != nil {
		return x.Removed
	}
	return false
}

var File_proto_URLShortenerV1_proto protoreflect.FileDescriptor

var file_proto_URLShortenerV1_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x55, 0x52, 0x4c, 0x53, 0x68, 0x6f, 0x72, 0x74,
	0x65, 0x6e, 0x65, 0x72, 0x56, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x70, 0x0a, 0x12,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x6c, 0x69, 0x6e, 0x6b, 0x52,
	0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x75, 0x72, 0x6c, 0x12, 0x31, 0x0a, 0x12, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x5f,
	0x69, 0x6e, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x48, 0x00, 0x52, 0x10, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x49, 0x6e, 0x53, 0x65, 0x63,
	0x6f, 0x6e, 0x64, 0x73, 0x88, 0x01, 0x01, 0x42, 0x15, 0x0a, 0x13, 0x5f, 0x65, 0x78, 0x70, 0x69,
	0x72, 0x65, 0x73, 0x5f, 0x69, 0x6e, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x22, 0x32,
	0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x6c, 0x69, 0x6e,
	0x6b, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f, 0x75,
	0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55,
	0x72, 0x6c, 0x22, 0x10, 0x0a, 0x0e, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63,
	0x70, 0x52, 0x65, 0x71, 0x22, 0x21, 0x0a, 0x0f, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x22, 0x31, 0x0a, 0x12, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x6c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a,
	0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x22, 0x2f, 0x0a, 0x13, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x6c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x32, 0xbe, 0x01, 0x0a, 0x0e,
	0x55, 0x52, 0x4c, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x56, 0x31, 0x12, 0x3c,
	0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x6c, 0x69, 0x6e,
	0x6b, 0x12, 0x13, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x6c,
	0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53,
	0x68, 0x6f, 0x72, 0x74, 0x6c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x12, 0x30, 0x0a, 0x0b,
	0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x0f, 0x2e, 0x48, 0x65,
	0x61, 0x6c, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x70, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x48,
	0x65, 0x61, 0x6c, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3c,
	0x0a, 0x0f, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x6c, 0x69, 0x6e,
	0x6b, 0x12, 0x13, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x6c,
	0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53,
	0x68, 0x6f, 0x72, 0x74, 0x6c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x42, 0x0b, 0x5a, 0x09,
	0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_URLShortenerV1_proto_rawDescOnce sync.Once
	file_proto_URLShortenerV1_proto_rawDescData = file_proto_URLShortenerV1_proto_rawDesc
)

func file_proto_URLShortenerV1_proto_rawDescGZIP() []byte {
	file_proto_URLShortenerV1_proto_rawDescOnce.Do(func() {
		file_proto_URLShortenerV1_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_URLShortenerV1_proto_rawDescData)
	})
	return file_proto_URLShortenerV1_proto_rawDescData
}

var file_proto_URLShortenerV1_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_URLShortenerV1_proto_goTypes = []interface{}{
	(*CreateShortlinkReq)(nil),  // 0: CreateShortlinkReq
	(*CreateShortlinkResp)(nil), // 1: CreateShortlinkResp
	(*HealthChecpReq)(nil),      // 2: HealthChecpReq
	(*HealthCheckResp)(nil),     // 3: HealthCheckResp
	(*RemoveShortlinkReq)(nil),  // 4: RemoveShortlinkReq
	(*RemoveShortlinkResp)(nil), // 5: RemoveShortlinkResp
}
var file_proto_URLShortenerV1_proto_depIdxs = []int32{
	0, // 0: URLShortenerV1.CreateShortlink:input_type -> CreateShortlinkReq
	2, // 1: URLShortenerV1.HealthCheck:input_type -> HealthChecpReq
	4, // 2: URLShortenerV1.RemoveShortlink:input_type -> RemoveShortlinkReq
	1, // 3: URLShortenerV1.CreateShortlink:output_type -> CreateShortlinkResp
	3, // 4: URLShortenerV1.HealthCheck:output_type -> HealthCheckResp
	5, // 5: URLShortenerV1.RemoveShortlink:output_type -> RemoveShortlinkResp
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_URLShortenerV1_proto_init() }
func file_proto_URLShortenerV1_proto_init() {
	if File_proto_URLShortenerV1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_URLShortenerV1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateShortlinkReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_URLShortenerV1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateShortlinkResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_URLShortenerV1_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HealthChecpReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_URLShortenerV1_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HealthCheckResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_URLShortenerV1_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveShortlinkReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_URLShortenerV1_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveShortlinkResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_URLShortenerV1_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_URLShortenerV1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_URLShortenerV1_proto_goTypes,
		DependencyIndexes: file_proto_URLShortenerV1_proto_depIdxs,
		MessageInfos:      file_proto_URLShortenerV1_proto_msgTypes,
	}.Build()
	File_proto_URLShortenerV1_proto = out.File
	file_proto_URLShortenerV1_proto_rawDesc = nil
	file_proto_URLShortenerV1_proto_goTypes = nil
	file_proto_URLShortenerV1_proto_depIdxs = nil
}
